// Embeds the coding-agent skill in the CLI as a TypeScript module, so the bundled CLI and the
// source CLI (tsx) both carry it. Run after editing plugins/furio/skills/furio-architecture/SKILL.md.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dirname, '..');
const skill = readFileSync(join(root, 'plugins/furio/skills/furio-architecture/SKILL.md'), 'utf8');
const target = join(root, 'packages/cli/src/skill.generated.ts');
writeFileSync(
  target,
  `// Generated by scripts/embed-skill.mjs from plugins/furio/skills/furio-architecture/SKILL.md.\n// Do not edit: edit the skill and run \`node scripts/embed-skill.mjs\`.\nexport const SKILL = ${JSON.stringify(skill)};\n`,
);
console.log(`Wrote ${target}`);
